### ISSUE TITLE
Add `next` field to login page

### ISSUE THREAD

**Issue by moshthepitt** [onaio/onadata-template#4]
Add a hidden `next` field to the login template.

something like 

```html
<input type="hidden" name="next" value="/dashboard/" />
```

The value of this field should be the url that the user should be sent to after logging in.  For example, in the above example code the user will be redirected to `/dashboard`

**Comment by ukanga** [comment]
How was it working before? And this makes the change such that every Oaut2 application will have to implement a `/dashboard` endpoint, that may not be an ideal solution.

**Comment by moshthepitt** [comment]
@ukanga My /dashboard thing up there is just an example.  I believe the `next` value is present in the context data passed to the template, so the actual implementation will be something like:

```html
<input type="hidden" name="next" value="{{ redirect_field_value }}" />
```

But I have not checked if the variable is called `redirect_field_value` - this will need to be confirmed when doing the fix.
